spring:
  # 静态资源处理
  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          # 缓存最大生存时间，单位是秒
          max-age: 3600
      chain:
        # 对整个静态资源链开启缓存
        cache: true
        # 启动资源链
        enabled: true
        # 启用压缩资源
        compressed: true
      static-locations: classpath:/static/


  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
    username: root
    password: twq1012
#    password: Tang_1012
    hikari:
      pool-name: hikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 10
      # 空闲连接的最大存活时间，单位为毫秒
      idle-timeout: 1800000
      # 连接最大存活时间
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 30000
      # 测试连接是否可用的查询语句（心跳机制）
      connection-test-query: SELECT 1
      auto-commit: true


  redis:
#    host: 47.102.197.62
    host: 127.0.0.1
    port: 6379
#    password: twq1012
    # 使用的数据库(指定下标)
    database: 0
    # 超时时间
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        # 最大连接阻塞超时时间
        max-wait: 10000ms
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 0


  rabbitmq:
    host: 47.102.197.62
    port: 5672
    username: twq
    password: twq1012
    virtual-host: /
    listener:
      simple:
        # 消费者的最小数量
        concurrency: 10
        # 消费者的最大数量
        max-concurrency: 10
        # 限制消费者每次只能预读一条消息（只有处理完当前消息，才能继续获取下一条消息）
        prefetch: 1
        # 启动时是否需要自动启动容器
        auto-startup: true
        # 当消息被拒绝时的执行策略。当配置为 true ，代表继续重新尝试进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 开启重试功能
        enabled: true
        # 重试时间
        initial-interval: 1000ms
        # 重试最大次数
        max-attempts: 3
        # 重试最大间隔时间
        max-interval: 10000ms


mybatis-plus:
  # 配置 Mapper.xml 映射文件的位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: cn.twq.secKill.entity


logging:
  # 将 Mybatis 的 SQL 语句打印在控制台上
  level:
    # 这是方法接口所在的包，不是 mapper.xml 所在的包
    cn.twq.secKill.mapper: debug
